#!/bin/sh
#
# fcgi
#
# chkconfig:	345 85 15
# description:	fcgi is a perl script to provide simple cgi support
# processname:	fcgi

ME=`basename $0`

CONFIG=/etc/default/$ME
if [ ! -f $CONFIG ]; then
	echo >&2 "fcgi: Missing $CONFIG config file"
	exit 1
else
	. $CONFIG
fi


checkconfig() {

	if [ -z "$SPAWN_UID" ]; then
		echo >&2 "$ME: Missing SPAWN_UID value (user name) in $CONFIG"
		exit 1
	fi

	if [ -z $SPAWN_GID ]; then
		echo >&2 "$ME: Missing SPAWN_GID value (group name) in $CONFIG"
		exit 1
	fi

	if [ -z "$SPAWN_LOG" ]; then
		echo >&2 "$ME: missing declaration of log file SPAWN_LOG in $CONFIG"
		exit 1
	fi

	if [ -z "$SPAWN_SOCKET" ]; then
		echo 2>&2 "$ME: missing SPAWN_SOCKET in $CONFIG"
	fi

	USER_ID=`id -u $SPAWN_UID 2>&1 > /dev/null`
	if [ $USER_ID -eq $USER_ID > /dev/null 2>&1 ]; then
		USER_ID=`id -u $SPAWN_UID`
	else
		echo >&2 "fcgi: $SPAWN_UID user not found in system"
		exit 1
	fi
}

start() {
	# Check if the service is already running?
	if [ ! -f /var/lock/subsys/$ME ]; then
		echo -n $ME: 
		
		start-stop-daemon --start --exec $FCGI_SCRIPT --group $SPAWN_GID --chuid $SPAWN_UID -- --pid $SPAWN_PID "$SPAWN_OPT" --socket $SPAWN_SOCKET --log $SPAWN_LOG
		RETVAL=$?
		if [ $RETVAL -eq 0 ]; then
			echo started
		else
			echo failed
		fi
	else
		echo already running $ME
	fi
}

stop() {
	# Stop daemons.
	start-stop-daemon --stop --pidfile $SPAWN_PID
	echo -n "$ME: "
		# Delete pidfile only when nginx was called successfully
		if [ $? -eq 0 ]; then
			rm -f /var/lock/subsys/$ME "$SPAWN_PID"  >/dev/null 2>&1
		fi
	echo "stopped"
}


RETVAL=0

case "$1" in
  start)
  	checkconfig
  	start
	;;
  stop)
  	stop
	;;
  status)
	status $ME
	RETVAL=$?
	;;
  restart)
	stop
	start
	;;
  *)
	echo "$0 {start|stop|restart|status}"
	exit 3
	;;
esac

exit $RETVAL
